A= int(input("Dame un numero entero"))
B= int(input("Dame otro numero entero"))
C= int(input("Dame un tercer numero entero"))
D= int(input("Dame un ultimo numero entero"))
print(f"El numero generado ordenandolos del ultimo al primero es {D} {C} {B} {A}")
